package com.zeroone.biospay;

import java.awt.Desktop;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.*;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import org.apache.poi.ss.usermodel.BorderStyle;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellStyle;
import org.apache.poi.ss.usermodel.HorizontalAlignment;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.ss.util.CellRangeAddress;
import org.apache.poi.ss.util.RegionUtil;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

public class CompletedPayments extends javax.swing.JFrame {
    
    ResultSet rs;
    Connection con;
    PreparedStatement pst;
    
    public CompletedPayments() {
        initComponents();
        con = SQLConnection.DBConnection();
        fetchSections();
        FetchCompletePayments();
    }
    
    public void Connect(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/paymentms","root","");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CompletedPayments.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(CompletedPayments.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void FetchCompletePayments(){
        try {
            // Getting Contribution DB ColumnName to Generate Query Automatically
            pst = con.prepareStatement("SELECT column_name from contributions;");
            rs = pst.executeQuery();

            StringBuilder columnData = new StringBuilder();
            while (rs.next()) {
                String columnName = rs.getString("column_name");
                columnData.append(columnName).append(" = 'PAYED' AND ");
            }
            
            String paymentQuery = columnData.toString();
            if (paymentQuery.endsWith(" AND ")) {
                paymentQuery = paymentQuery.substring(0, paymentQuery.length() - 5);
            } else {
                return; // HandleError
            }
            
            // Showing Students List if Fully Paid
            pst = con.prepareStatement("SELECT payments.student_id, users.name, users.section, users.email FROM payments INNER JOIN users ON payments.student_id = users.student_id WHERE " + paymentQuery + ";");
            rs = pst.executeQuery();

            ResultSetMetaData rss = rs.getMetaData();
            int q = rss.getColumnCount();

            DefaultTableModel df = (DefaultTableModel) jTableCompPayments.getModel();
            df.setRowCount(0);
            while(rs.next()){
                Vector v2 = new Vector();
                for(int a=1; a<=q; a++){
                    v2.add(rs.getString("student_id"));
                    v2.add(rs.getString("name"));
                    v2.add(rs.getString("section"));
                    v2.add(rs.getString("email"));
                }
                df.addRow(v2);
            }
        } catch (SQLException ex) {
            Logger.getLogger(CompletedPayments.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void fetchSections(){
        try {
            pst = con.prepareStatement("SELECT section FROM sections");
            rs = pst.executeQuery();
            cbxSections.removeAllItems();
            while(rs.next()){
                cbxSections.addItem(rs.getString(1));
            }
        } catch (SQLException ex) {
            Logger.getLogger(CompletedPayments.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void openFile(String file){
        try{
            File path = new File(file);
            Desktop.getDesktop().open(path);
        }catch(IOException ioe){
            System.out.println(ioe);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCompPayments = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        txtFieldSearch = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        HeaderJPanel = new javax.swing.JPanel();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnSaveXLS = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        btnFilterSections = new javax.swing.JButton();
        cbxSections = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("COMPLETE PAYMENTS | BIOSPAY");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(690, 484));
        jPanel1.setMinimumSize(new java.awt.Dimension(690, 484));
        jPanel1.setPreferredSize(new java.awt.Dimension(690, 484));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableCompPayments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STUDENT ID", "NAME", "SECTION", "EMAIL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableCompPayments.setRowHeight(40);
        jScrollPane1.setViewportView(jTableCompPayments);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 970, 540));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(3, 83, 164));
        jLabel6.setText("SEARCH");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 30));

        txtFieldSearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtFieldSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFieldSearchKeyReleased(evt);
            }
        });
        jPanel1.add(txtFieldSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 330, 30));

        btnBack.setBackground(new java.awt.Color(3, 83, 164));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 10, 150, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 970, 590));

        HeaderJPanel.setBackground(new java.awt.Color(3, 83, 164));
        HeaderJPanel.setPreferredSize(new java.awt.Dimension(0, 60));
        HeaderJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("COMPLETED PAYMENTS | BIOSPAY");
        HeaderJPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 330, 40));

        getContentPane().add(HeaderJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, -1));

        jPanel2.setBackground(new java.awt.Color(3, 83, 164));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(3, 83, 164));
        jPanel3.setForeground(new java.awt.Color(3, 83, 164));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSaveXLS.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnSaveXLS.setForeground(new java.awt.Color(3, 83, 164));
        btnSaveXLS.setText("EXPORT AS XLS");
        btnSaveXLS.setToolTipText("");
        btnSaveXLS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveXLSActionPerformed(evt);
            }
        });
        jPanel3.add(btnSaveXLS, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 210, 43));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("FILTER SECTIONS");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 210, -1));

        btnFilterSections.setBackground(new java.awt.Color(204, 0, 0));
        btnFilterSections.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnFilterSections.setForeground(new java.awt.Color(255, 255, 255));
        btnFilterSections.setText("FILTER SECTIONS");
        btnFilterSections.setToolTipText("");
        btnFilterSections.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilterSectionsActionPerformed(evt);
            }
        });
        jPanel3.add(btnFilterSections, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 210, 30));

        cbxSections.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BSIT 3A", "BSIT 3B", "BSIT 3C" }));
        jPanel3.add(cbxSections, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 210, 30));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -10, 210, 450));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 230, 590));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveXLSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveXLSActionPerformed
        try{
            JFileChooser jFileChooser = new JFileChooser();
            jFileChooser.showSaveDialog(this);
            File saveFile = jFileChooser.getSelectedFile();
           
            if(saveFile != null){
                saveFile = new File(saveFile.toString()+".xlsx");
                Workbook wb = new XSSFWorkbook();
                Sheet sheet = wb.createSheet("Complete Payments");
                CellStyle centeredStyle = wb.createCellStyle();

                // Set border for the style
                centeredStyle.setBorderBottom(BorderStyle.THIN);
                centeredStyle.setBorderTop(BorderStyle.THIN);
                centeredStyle.setBorderLeft(BorderStyle.THIN);
                centeredStyle.setBorderRight(BorderStyle.THIN);

                // Set horizontal alignment to center
                centeredStyle.setAlignment(HorizontalAlignment.CENTER);

                //Create a cell for the label "ATTENDANCE" and merge cells
                Row labelRow = sheet.createRow(0);
                Cell labelCell = labelRow.createCell(0);
                labelCell.setCellValue("COMPLETE PAYMENTS");
                labelCell.setCellStyle(centeredStyle);
                sheet.addMergedRegion(new CellRangeAddress(0, 0, 0, jTableCompPayments.getColumnCount() - 1));

                // Apply borders to the merged cell containing "ATTENDANCE" label
                RegionUtil.setBorderBottom(BorderStyle.THIN, new CellRangeAddress(0, 0, 0, jTableCompPayments.getColumnCount() - 1), sheet);
                RegionUtil.setBorderTop(BorderStyle.THIN, new CellRangeAddress(0, 0, 0, jTableCompPayments.getColumnCount() - 1), sheet);
                RegionUtil.setBorderLeft(BorderStyle.THIN, new CellRangeAddress(0, 0, 0, jTableCompPayments.getColumnCount() - 1), sheet);
                RegionUtil.setBorderRight(BorderStyle.THIN, new CellRangeAddress(0, 0, 0, jTableCompPayments.getColumnCount() - 1), sheet);

                Row rowCol = sheet.createRow(1);
                for(int i=0;i<jTableCompPayments.getColumnCount();i++){
                   Cell cell = rowCol.createCell(i);
                   cell.setCellValue(jTableCompPayments.getColumnName(i));
                }

                for(int j=0;j<jTableCompPayments.getRowCount();j++){
                   Row row = sheet.createRow(j+1);
                   for(int k=0;k<jTableCompPayments.getColumnCount();k++){
                       Cell cell = row.createCell(k);
                       if(jTableCompPayments.getValueAt(j, k)!=null){
                           cell.setCellValue(jTableCompPayments.getValueAt(j, k).toString());
                       }
                   }
                }

                for (int i = 0; i < jTableCompPayments.getColumnCount(); i++) {
                   sheet.autoSizeColumn(i);
                }

                // Apply borders to all cells containing data
                for (int j = 0; j < jTableCompPayments.getRowCount(); j++) {
                    Row row = sheet.createRow(j + 1);
                    for (int k = 0; k < jTableCompPayments.getColumnCount(); k++) {
                        Cell cell = row.createCell(k);
                        if (jTableCompPayments.getValueAt(j, k) != null) {
                            cell.setCellValue(jTableCompPayments.getValueAt(j, k).toString());
                            cell.setCellStyle(centeredStyle); // Apply the style to the cell
                        }
                        // Set auto-size column for the cell
                        sheet.autoSizeColumn(k);
                    }
                }

               FileOutputStream out = new FileOutputStream(new File(saveFile.toString()));
               wb.write(out);
               wb.close();
               out.close();
               openFile(saveFile.toString());
            }else{
               JOptionPane.showMessageDialog(null,"Cancelled to Export");
            }
        }catch(FileNotFoundException e){
           System.out.println(e);
        }catch(IOException io){
           System.out.println(io);
        }
    }//GEN-LAST:event_btnSaveXLSActionPerformed

    private void btnFilterSectionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilterSectionsActionPerformed
        //Getting Data from JComboBox
        String section = cbxSections.getSelectedItem().toString();
        DefaultTableModel model = (DefaultTableModel) jTableCompPayments.getModel();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        jTableCompPayments.setRowSorter(sorter);

        RowFilter<DefaultTableModel, Object> rowFilter = RowFilter.regexFilter("(?i)" + section);
        sorter.setRowFilter(rowFilter);
    }//GEN-LAST:event_btnFilterSectionsActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        Payments payment = new Payments();
        payment.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        FetchCompletePayments();
    }//GEN-LAST:event_formWindowActivated

    private void txtFieldSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFieldSearchKeyReleased
        String searchText = txtFieldSearch.getText();
        DefaultTableModel model = (DefaultTableModel) jTableCompPayments.getModel();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        jTableCompPayments.setRowSorter(sorter);

        RowFilter<DefaultTableModel, Object> rowFilter = RowFilter.regexFilter("(?i)" + searchText);
        sorter.setRowFilter(rowFilter);
    }//GEN-LAST:event_txtFieldSearchKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CompletedPayments().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel HeaderJPanel;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnFilterSections;
    private javax.swing.JButton btnSaveXLS;
    private javax.swing.JComboBox<String> cbxSections;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCompPayments;
    private javax.swing.JTextField txtFieldSearch;
    // End of variables declaration//GEN-END:variables
}
