package com.zeroone.biospay;

import java.sql.*;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

public class Payments extends javax.swing.JFrame {
    
    ResultSet rs;
    Connection con;
    PreparedStatement pst;
    
    public Payments() {
        initComponents();
        con = SQLConnection.DBConnection();
        fetchSections();
        FetchPayments();
    }
    
    public void Connect(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/paymentms","root","");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Payments.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Payments.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void FetchPayments(){
        try {
            // Getting Contribution DB ColumnName to Generate Query Automatically
            pst = con.prepareStatement("SELECT column_name from contributions;");
            rs = pst.executeQuery();

            StringBuilder columnData = new StringBuilder();
            while (rs.next()) {
                String columnName = rs.getString("column_name");
                columnData.append(columnName).append(", ");
            }
            String paymentQuery = columnData.toString();
            if (paymentQuery.endsWith(", ")) {
                paymentQuery = paymentQuery.substring(0, paymentQuery.length() - 2);
            } else {
                return; // HandleError
            }
            
            // Showing Students List if Fully Paid
            pst = con.prepareStatement("SELECT payments.student_id, users.name, users.section, " + paymentQuery + " FROM payments INNER JOIN users ON payments.student_id = users.student_id;");
            rs = pst.executeQuery();

            ResultSetMetaData rss = rs.getMetaData();
            int q = rss.getColumnCount();

            DefaultTableModel df = (DefaultTableModel) jTablePayments.getModel();
            // Clear existing rows and columns in the table model
            df.setRowCount(0);
            df.setColumnCount(0);

            for (int i = 1; i <= q; i++) {
                String columnName = rss.getColumnName(i);
                columnName = columnName.replace("_", " ").toUpperCase();
                df.addColumn(columnName);
            }

            while (rs.next()) {
                Object[] rowData = new Object[q];
                for (int i = 0; i < q; i++) {
                    rowData[i] = rs.getObject(i + 1);
                }
                df.addRow(rowData);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Payments.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void fetchSections(){
        try {
            pst = con.prepareStatement("SELECT section FROM sections");
            rs = pst.executeQuery();
            cbxSections.removeAllItems();
            while(rs.next()){
                cbxSections.addItem(rs.getString(1));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Payments.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePayments = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        txtFieldSearch = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        HeaderJPanel = new javax.swing.JPanel();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnPayContribution = new javax.swing.JButton();
        btnCompletedPayments = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        btnFilterSections = new javax.swing.JButton();
        cbxSections = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PAYMENTS | BIOSPAY");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(690, 484));
        jPanel1.setMinimumSize(new java.awt.Dimension(690, 484));
        jPanel1.setPreferredSize(new java.awt.Dimension(690, 484));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTablePayments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTablePayments.setRowHeight(40);
        jScrollPane1.setViewportView(jTablePayments);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 970, 540));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(3, 83, 164));
        jLabel6.setText("SEARCH");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 30));

        txtFieldSearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtFieldSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFieldSearchKeyReleased(evt);
            }
        });
        jPanel1.add(txtFieldSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 330, 30));

        btnBack.setBackground(new java.awt.Color(3, 83, 164));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 10, 150, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 970, 590));

        HeaderJPanel.setBackground(new java.awt.Color(3, 83, 164));
        HeaderJPanel.setPreferredSize(new java.awt.Dimension(0, 60));
        HeaderJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PAYMENTS | BIOSPAY");
        HeaderJPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 294, 40));

        getContentPane().add(HeaderJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, -1));

        jPanel2.setBackground(new java.awt.Color(3, 83, 164));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(3, 83, 164));
        jPanel3.setForeground(new java.awt.Color(3, 83, 164));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPayContribution.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnPayContribution.setForeground(new java.awt.Color(3, 83, 164));
        btnPayContribution.setText("PAY CONTRIBUTION");
        btnPayContribution.setToolTipText("");
        btnPayContribution.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayContributionActionPerformed(evt);
            }
        });
        jPanel3.add(btnPayContribution, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 210, 46));

        btnCompletedPayments.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnCompletedPayments.setForeground(new java.awt.Color(3, 83, 164));
        btnCompletedPayments.setText("COMPLETED PAYMENTS");
        btnCompletedPayments.setToolTipText("");
        btnCompletedPayments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompletedPaymentsActionPerformed(evt);
            }
        });
        jPanel3.add(btnCompletedPayments, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 210, 43));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("FILTER SECTIONS");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 210, -1));

        btnFilterSections.setBackground(new java.awt.Color(204, 0, 0));
        btnFilterSections.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnFilterSections.setForeground(new java.awt.Color(255, 255, 255));
        btnFilterSections.setText("FILTER SECTIONS");
        btnFilterSections.setToolTipText("");
        btnFilterSections.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilterSectionsActionPerformed(evt);
            }
        });
        jPanel3.add(btnFilterSections, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 210, 30));

        cbxSections.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BSIT 3A", "BSIT 3B", "BSIT 3C" }));
        jPanel3.add(cbxSections, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 210, 30));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -10, 210, 450));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 230, 590));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCompletedPaymentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompletedPaymentsActionPerformed
        CompletedPayments compPayments = new CompletedPayments();
        compPayments.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCompletedPaymentsActionPerformed

    private void btnPayContributionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayContributionActionPerformed
        PayContribution pay = new PayContribution();
        pay.setVisible(true);
    }//GEN-LAST:event_btnPayContributionActionPerformed

    private void btnFilterSectionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilterSectionsActionPerformed
        //Getting Data from JComboBox
        String section = cbxSections.getSelectedItem().toString();
        DefaultTableModel model = (DefaultTableModel) jTablePayments.getModel();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        jTablePayments.setRowSorter(sorter);

        RowFilter<DefaultTableModel, Object> rowFilter = RowFilter.regexFilter("(?i)" + section);
        sorter.setRowFilter(rowFilter);
    }//GEN-LAST:event_btnFilterSectionsActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        Dashboard mainmenu = new Dashboard();
        mainmenu.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        FetchPayments();
    }//GEN-LAST:event_formWindowActivated

    private void txtFieldSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFieldSearchKeyReleased
        String searchText = txtFieldSearch.getText();
        DefaultTableModel model = (DefaultTableModel) jTablePayments.getModel();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        jTablePayments.setRowSorter(sorter);

        RowFilter<DefaultTableModel, Object> rowFilter = RowFilter.regexFilter("(?i)" + searchText);
        sorter.setRowFilter(rowFilter);
    }//GEN-LAST:event_txtFieldSearchKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payments().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel HeaderJPanel;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCompletedPayments;
    private javax.swing.JButton btnFilterSections;
    private javax.swing.JButton btnPayContribution;
    private javax.swing.JComboBox<String> cbxSections;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePayments;
    private javax.swing.JTextField txtFieldSearch;
    // End of variables declaration//GEN-END:variables
}
