package com.zeroone.biospay;

import java.sql.*;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

//QRCode
import com.google.zxing.BarcodeFormat;
import com.google.zxing.WriterException;
import com.google.zxing.client.j2se.MatrixToImageWriter;
import com.google.zxing.common.BitMatrix;
import com.google.zxing.qrcode.QRCodeWriter;
import java.io.IOException;
import java.nio.file.FileSystems;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import javax.swing.JOptionPane;

public class Users extends javax.swing.JFrame {
    
    ResultSet rs;
    Connection con;
    PreparedStatement pst;
    
    public Users() {
        initComponents();
        con = SQLConnection.DBConnection();
        fetchSections();
        Fetch();
    }
    
    private void Fetch(){
        try {
            int q;
            
            pst = con.prepareStatement("SELECT * FROM users");
            rs = pst.executeQuery();
            
            ResultSetMetaData rss = rs.getMetaData();
            q = rss.getColumnCount();
            
            DefaultTableModel df = (DefaultTableModel)jTableUsers.getModel();
            df.setRowCount(0);
            while(rs.next()){
                Vector v2 = new Vector();
                for(int a=1; a<=q; a++){
                    v2.add(rs.getString("student_id"));
                    v2.add(rs.getString("name"));
                    v2.add(rs.getString("section"));
                    v2.add(rs.getString("email"));
                }
                df.addRow(v2);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Users.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void fetchSections(){
        try {
            pst = con.prepareStatement("SELECT section FROM sections");
            rs = pst.executeQuery();
            cbxSections.removeAllItems();
            while(rs.next()){
                cbxSections.addItem(rs.getString(1));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Users.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void generateQRCode(){
        int rowCount = jTableUsers.getRowCount();
        
        String directoryPath = "D:\\qrcodes\\";
        int width = 1250;
        int height = 1250;

        QRCodeWriter qc = new QRCodeWriter();
        for (int i = 0; i < rowCount; i++) {
            String studentID = jTableUsers.getValueAt(i, 0).toString();
            String name = jTableUsers.getValueAt(i, 1).toString();
            String section = jTableUsers.getValueAt(i, 2).toString();
            String fileName = studentID + " - " +  section + " - " + name + ".png";
            String sectionDirectory = directoryPath + section + "\\";
            String filePath = directoryPath + fileName;

            try {
                // Create directory if it doesn't exist
                Path directory = FileSystems.getDefault().getPath(sectionDirectory);
                Files.createDirectories(directory);
                
                //Process of Generate
                BitMatrix bm = qc.encode(studentID, BarcodeFormat.QR_CODE, width, height);
                Path pobj = FileSystems.getDefault().getPath(filePath);
                MatrixToImageWriter.writeToPath(bm, "PNG", pobj);
                
                 // Move the generated QR code to the section directory
                Path sourcePath = FileSystems.getDefault().getPath(filePath);
                Path destinationPath = FileSystems.getDefault().getPath(sectionDirectory, fileName);
                Files.move(sourcePath, destinationPath, StandardCopyOption.REPLACE_EXISTING);
            
            } catch (WriterException | IOException ex) {
                ex.printStackTrace();
            }
        }
        JOptionPane.showMessageDialog(this, "QR codes generated and saved successfully!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableUsers = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        txtFieldSearch = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        HeaderJPanel = new javax.swing.JPanel();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnGenerateQR = new javax.swing.JButton();
        btnAddUser = new javax.swing.JButton();
        btnEditDeleteUser = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        btnFilterSections = new javax.swing.JButton();
        cbxSections = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("USERS | BIOSPAY");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(690, 484));
        jPanel1.setMinimumSize(new java.awt.Dimension(690, 484));
        jPanel1.setPreferredSize(new java.awt.Dimension(690, 484));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "STUDENT ID", "NAME", "SECTION", "EMAIL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableUsers.setRowHeight(40);
        jScrollPane1.setViewportView(jTableUsers);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 970, 540));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(3, 83, 164));
        jLabel6.setText("SEARCH");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 30));

        txtFieldSearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtFieldSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFieldSearchKeyReleased(evt);
            }
        });
        jPanel1.add(txtFieldSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 330, 30));

        btnBack.setBackground(new java.awt.Color(3, 83, 164));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 10, 150, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 970, 590));

        HeaderJPanel.setBackground(new java.awt.Color(3, 83, 164));
        HeaderJPanel.setPreferredSize(new java.awt.Dimension(0, 60));
        HeaderJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("USERS | BIOSPAY");
        HeaderJPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 294, 40));

        getContentPane().add(HeaderJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, -1));

        jPanel2.setBackground(new java.awt.Color(3, 83, 164));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(3, 83, 164));
        jPanel3.setForeground(new java.awt.Color(3, 83, 164));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGenerateQR.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnGenerateQR.setForeground(new java.awt.Color(3, 83, 164));
        btnGenerateQR.setText("GENERATE QR CODE");
        btnGenerateQR.setToolTipText("");
        btnGenerateQR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateQRActionPerformed(evt);
            }
        });
        jPanel3.add(btnGenerateQR, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 210, 46));

        btnAddUser.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnAddUser.setForeground(new java.awt.Color(3, 83, 164));
        btnAddUser.setText("ADD USER");
        btnAddUser.setToolTipText("");
        btnAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddUserActionPerformed(evt);
            }
        });
        jPanel3.add(btnAddUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 210, 46));

        btnEditDeleteUser.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnEditDeleteUser.setForeground(new java.awt.Color(3, 83, 164));
        btnEditDeleteUser.setText("EDIT/DELETE USER");
        btnEditDeleteUser.setToolTipText("");
        btnEditDeleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditDeleteUserActionPerformed(evt);
            }
        });
        jPanel3.add(btnEditDeleteUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 210, 43));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("FILTER SECTIONS");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 210, -1));

        btnFilterSections.setBackground(new java.awt.Color(204, 0, 0));
        btnFilterSections.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnFilterSections.setForeground(new java.awt.Color(255, 255, 255));
        btnFilterSections.setText("FILTER SECTIONS");
        btnFilterSections.setToolTipText("");
        btnFilterSections.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilterSectionsActionPerformed(evt);
            }
        });
        jPanel3.add(btnFilterSections, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 210, 30));

        cbxSections.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BSIT 3A", "BSIT 3B", "BSIT 3C" }));
        jPanel3.add(cbxSections, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 210, 30));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -10, 210, 450));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 230, 590));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditDeleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditDeleteUserActionPerformed
        EditDeleteUser updateUser = new EditDeleteUser();
        updateUser.setVisible(true);
    }//GEN-LAST:event_btnEditDeleteUserActionPerformed

    private void btnAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddUserActionPerformed
        AddUser user = new AddUser();
        user.setVisible(true);
    }//GEN-LAST:event_btnAddUserActionPerformed

    private void btnFilterSectionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilterSectionsActionPerformed
        //Getting Data from JComboBox
        String section = cbxSections.getSelectedItem().toString();
        DefaultTableModel model = (DefaultTableModel) jTableUsers.getModel();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        jTableUsers.setRowSorter(sorter);

        RowFilter<DefaultTableModel, Object> rowFilter = RowFilter.regexFilter("(?i)" + section);
        sorter.setRowFilter(rowFilter);
    }//GEN-LAST:event_btnFilterSectionsActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        Dashboard mainmenu = new Dashboard();
        mainmenu.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Fetch();
    }//GEN-LAST:event_formWindowActivated

    private void txtFieldSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFieldSearchKeyReleased
        String searchText = txtFieldSearch.getText();
        DefaultTableModel model = (DefaultTableModel) jTableUsers.getModel();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        jTableUsers.setRowSorter(sorter);

        RowFilter<DefaultTableModel, Object> rowFilter = RowFilter.regexFilter("(?i)" + searchText);
        sorter.setRowFilter(rowFilter);
    }//GEN-LAST:event_txtFieldSearchKeyReleased

    private void btnGenerateQRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateQRActionPerformed
        generateQRCode();
    }//GEN-LAST:event_btnGenerateQRActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Users().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel HeaderJPanel;
    private javax.swing.JButton btnAddUser;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnEditDeleteUser;
    private javax.swing.JButton btnFilterSections;
    private javax.swing.JButton btnGenerateQR;
    private javax.swing.JComboBox<String> cbxSections;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableUsers;
    private javax.swing.JTextField txtFieldSearch;
    // End of variables declaration//GEN-END:variables
}
